infix using "C:\COUNTRIES\IA71\IAPR71FL.dct"

label variable hhid     "Case Identification"
label variable hvidx    "Line number"
label variable hv000    "Country code and phase"
label variable hv001    "Cluster number"
label variable hv002    "Household number"
label variable hv003    "Respondent's line number (answering Household questionnaire)"
label variable hv004    "Ultimate area unit"
label variable hv005    "Household sample weight (6 decimals)"
label variable hv006    "Month of interview"
label variable hv007    "Year of interview"
label variable hv008    "Date of interview (CMC)"
label variable hv009    "Number of household members"
label variable hv010    "Number of eligible women in household"
label variable hv011    "Number of eligible men in household"
label variable hv012    "Number of de jure members"
label variable hv013    "Number of de facto members"
label variable hv014    "Number of children 5 and under (de jure)"
label variable hv015    "Result of household interview"
label variable hv016    "Day of interview"
label variable hv017    "Number of visits"
label variable hv018    "Interviewer identification"
label variable hv019    "NA - Keyer identification"
label variable hv020    "Ever-married sample"
label variable hv021    "Primary sampling unit"
label variable hv022    "Sample strata for sampling errors"
label variable hv023    "Stratification used in sample design"
label variable hv024    "State"
label variable hv025    "Type of place of residence"
label variable hv026    "NA - Place of residence"
label variable hv027    "Household selected for male interview"
label variable hv028    "Household weight for male subsample (6 decimals)"
label variable hv030    "Field supervisor"
label variable hv031    "NA - Field editor"
label variable hv032    "NA - Office editor"
label variable hv035    "Number of eligible children for height and weight"
label variable hv040    "Cluster altitude in meters"
label variable hv041    "Total adults measured"
label variable hv042    "Household selected for hemoglobin"
label variable hv044    "Household selected for Domestic Violence module"
label variable hv201    "Source of drinking water"
label variable hv202    "NA - Source of non-drinking water"
label variable hv204    "Time to get to water source (minutes)"
label variable hv205    "Type of toilet facility"
label variable hv206    "Has electricity"
label variable hv207    "Has radio"
label variable hv208    "Has television"
label variable hv209    "Has refrigerator"
label variable hv210    "Has bicycle"
label variable hv211    "Has motorcycle/scooter"
label variable hv212    "Has car/truck"
label variable hv213    "Main floor material"
label variable hv214    "Main wall material"
label variable hv215    "Main roof material"
label variable hv216    "Number of rooms used for sleeping"
label variable hv217    "Relationship structure"
label variable hv218    "Line number of head of household"
label variable hv219    "Sex of head of household"
label variable hv220    "Age of head of household"
label variable hv221    "Has telephone (land-line)"
label variable hv225    "Share toilet with other households"
label variable hv226    "Type of cooking fuel"
label variable hv227    "Has mosquito bed net for sleeping"
label variable hv228    "Children under 5 slept under mosquito bed net last night"
label variable hv230a   "Place where household members wash their hands"
label variable hv230b   "Presence of water at hand washing place"
label variable hv232    "Items present: Soap or detergent"
label variable hv232b   "Items present: Ash, mud, sand"
label variable hv232c   "NA - Items present: CS"
label variable hv232d   "NA - Items present: CS"
label variable hv232e   "NA - Items present: CS"
label variable hv232y   "Items present: None"
label variable hv234    "NA - Result of salt test for iodine (PPM)"
label variable hv234a   "Result of salt test for iodine"
label variable hv235    "Location of source for water"
label variable hv236    "Person fetching water"
label variable hv237    "Anything done to water to make safe to drink"
label variable hv237a   "Water usually treated by: boil"
label variable hv237b   "Water usually treated by: add bleach/chlorine"
label variable hv237c   "Water usually treated by: strain through a cloth"
label variable hv237d   "Water usually treated by: use water filter"
label variable hv237e   "NA - Water usually treated by: solar disinfection"
label variable hv237f   "Water usually treated by: let it stand and settle"
label variable hv237g   "Water usually treated by: use alum"
label variable hv237h   "Water usually treated by: use electric purifier"
label variable hv237i   "NA - Water usually treated by: CS"
label variable hv237j   "NA - Water usually treated by: CS"
label variable hv237k   "NA - Water usually treated by: CS"
label variable hv237x   "Water usually treated by: other"
label variable hv237z   "Water usually treated by: don't know"
label variable hv238    "Number of households sharing toilet"
label variable hv239    "Food cooked on stove or open fire  (see SH39)"
label variable hv240    "NA - Household has a chimney, hood or neither"
label variable hv241    "Food cooked in the house/separate building/outdoors"
label variable hv242    "Household has separate room used as kitchen"
label variable hv243a   "Has mobile telephone"
label variable hv243b   "Has watch"
label variable hv243c   "Has animal-drawn cart"
label variable hv243d   "NA - Has boat with a motor"
label variable hv244    "Owns land usable for agriculture"
label variable hv245    "Hectares of agricultural land (1 decimal)  (see: HV245I, SH50 and SH51)"
label variable hv246    "Owns livestock, herds or farm animals"
label variable hv246a   "NA - Owns cattle"
label variable hv246b   "NA - Owns cows/bulls"
label variable hv246c   "NA - Owns horses/donkeys/mules"
label variable hv246d   "NA - Owns goats"
label variable hv246e   "NA - Owns sheep"
label variable hv246f   "NA - Owns chickens"
label variable hv246g   "NA - Owns CS"
label variable hv246h   "NA - Owns CS"
label variable hv246i   "NA - Owns CS"
label variable hv246j   "NA - Owns CS"
label variable hv246k   "NA - Owns CS"
label variable hv247    "Has bank account"
label variable hv252    "Frequency household members smoke inside the house"
label variable hv253    "NA - Has dwelling been sprayed against mosquitoes in last 12 months"
label variable hv253a   "NA - Dwelling sprayed by: government worker/program"
label variable hv253b   "NA - Dwelling sprayed by: private company"
label variable hv253c   "NA - Dwelling sprayed by: NGO"
label variable hv253d   "NA - Dwelling sprayed by: CS"
label variable hv253e   "NA - Dwelling sprayed by: CS"
label variable hv253f   "NA - Dwelling sprayed by: CS"
label variable hv253g   "NA - Dwelling sprayed by: CS"
label variable hv253h   "NA - Dwelling sprayed by: CS"
label variable hv253x   "NA - Dwelling sprayed by: other"
label variable hv253z   "NA - Dwelling sprayed by: don't know"
label variable hv270    "Wealth index"
label variable hv271    "Wealth index factor score (5 decimals)"
label variable hml1     "Number of mosquito bed nets"
label variable hml1a    "Number of mosquito bed nets with specific information"
label variable hml2     "Number of children under mosquito bed net previous night"
label variable shv005   "State household weight (6 decimals)"
label variable shv028   "State weight for households selected for men's sub-sample (6 decimals)"
label variable shdistri "District"
label variable shslumc  "Slum designation by sample frame"
label variable shslumo  "Slum designation by observation"
label variable shconsent "Consent agreement"
label variable shlangq  "Language of questionnaire"
label variable shlangrm "Respondent's mother tongue"
label variable shlangi  "Language of the interview"
label variable shtransl "Translator used?"
label variable sh23     "Any usual resident of the household suffers from TB"
label variable sh34     "Household head's religion"
label variable sh35     "Caste or tribe of household head"
label variable sh36     "Type of caste or tribe of the household head"
label variable sh37b    "Mattress"
label variable sh37c    "Pressure cooker"
label variable sh37d    "Chair"
label variable sh37e    "Cot or bed"
label variable sh37f    "Table"
label variable sh37g    "Electric fan"
label variable sh37i    "Black and white television"
label variable sh37j    "Colour television"
label variable sh37k    "Sewing machine"
label variable sh37n    "Internet"
label variable sh37o    "Computer"
label variable sh37q    "Air conditioner/cooler"
label variable sh37r    "Washing machine"
label variable sh37x    "Water pump"
label variable sh37y    "Thresher"
label variable sh37z    "Tractor"
label variable sh46     "Member of household owns this house or any other house"
label variable sh47     "Gender of person owning house"
label variable sh49     "Gender of person owning agricultural land"
label variable hv245i   "Hectares of irrigated agricultural land (1 decimal)  (see: HV245, SH50 and SH51)"
label variable sh52a    "Cows/bulls/buffaloes"
label variable sh52b    "Camels"
label variable sh52c    "Horses/donkeys/mules"
label variable sh52d    "Goats"
label variable sh52e    "Sheep"
label variable sh52f    "Chickens/ducks"
label variable sh54     "Member of household covered by a health scheme or health insurance"
label variable sh55a    "Health scheme/insurance: ESIS"
label variable sh55b    "Health scheme/insurance: CGHS"
label variable sh55c    "Health scheme/insurance: State health insurance scheme"
label variable sh55d    "Health scheme/insurance: Rashtriya Swasthya Bima Yojana (RSBY)"
label variable sh55e    "Health scheme/insurance: Comm Health Insurance Programme"
label variable sh55f    "Health scheme/insurance: other health insurance through employer"
label variable sh55g    "Health scheme/insurance: Medical reimbursement from employer"
label variable sh55h    "Health scheme/insurance: other privately purchased comm health insurance"
label variable sh55x    "Health scheme/insurance: other"
label variable sh56     "Where household members generally go for treatment"
label variable sh57a    "Reason HH members don't use govt facility: No nearby facility"
label variable sh57b    "Reason HH members don't use govt facility: Facility timing not convenient"
label variable sh57c    "Reason HH members don't use govt facility: Health personnel often absent"
label variable sh57d    "Reason HH members don't use govt facility: Waiting time too long"
label variable sh57e    "Reason HH members don't use govt facility: Poor quality of care"
label variable sh57x    "Reason HH members don't use govt facility: other"
label variable sh58     "Household has a BPL card"
label variable sh61a    "Place mosquito nets came from: Purchased from market"
label variable sh61b    "Place mosquito nets came from: Government"
label variable sh61c    "Place mosquito nets came from: Supplied by NGO/trust"
label variable sh61x    "Place mosquito nets came from: other"
label variable sh61z    "Place mosquito nets came from: Don't know"
label variable sh70     "Any usual member of the household died since January 2011"
label variable sh71     "Total number of deaths since January 2011"
label variable sh39     "In this household, is food cooked on a stove, a chullah or an open fire?"
label variable shnfhs2  "House type (as defined in NFHS-2 and 3)"
label variable shstruc  "Household structure"
label variable sh50     "Agricultural land (WITHOUT units specified) (1 decimal)  (see: SH50U)"
label variable sh51     "Irrigated agricultural land (WITHOUT units specified) (1 decimal)  (see: SH50U)"
label variable agland   "Agricultural land status"
label variable sv270s   "Wealth index within state"
label variable sv270u   "Wealth index - urban"
label variable sv271u   "Wealth index factor score (5 decimals) - urban"
label variable sv270us  "Wealth index - urban within state"
label variable sv270r   "Wealth index - rural"
label variable sv271r   "Wealth index factor score (5 decimals) - rural"
label variable sv270rs  "Wealth index - rural within state"
label variable sh50u    "Unit of measurement for agricultural land (see: SH50 and SH51)"
label variable shphase  "Questionnaire version: education questions"
label variable hv101    "Relationship to head"
label variable hv102    "Usual resident"
label variable hv103    "Slept last night"
label variable hv104    "Sex of household member"
label variable hv105    "Age of household members"
label variable hv106    "Highest educational level attained"
label variable hv107    "Highest year of education completed"
label variable hv108    "Education completed in single years"
label variable hv109    "Educational attainment"
label variable hv110    "NA - Member still in school"
label variable hv111    "Mother alive"
label variable hv112    "Mother's line number"
label variable hv113    "Father alive"
label variable hv114    "Father's line number"
label variable hv115    "Current marital status"
label variable hv116    "Currently, formerly, never married"
label variable hv117    "Eligibility for female interview"
label variable hv118    "Eligibility for male interview"
label variable hv120    "Children eligibility for height/weight and hemoglobin"
label variable hv121    "Member attended school during current school year"
label variable hv122    "Educational level during current school year"
label variable hv123    "Grade of education during current school year"
label variable hv124    "Education in single years - current school year"
label variable hv125    "NA - Member attended school during previous school year"
label variable hv126    "NA - Educational level during previous school year"
label variable hv127    "NA - Grade of education during previous school year"
label variable hv128    "NA - Education in single years - previous school year"
label variable hv129    "NA - School attendance status"
label variable hv140    "Member has a birth certificate"
label variable idxh4    "Index to Household Schedule"
label variable sh08     "Current marital status [age 13+]"
label variable sh21a    "Aadhaar/ID card"
label variable sh24     "Suffers from TB"
label variable sh24a    "Location where treated for TB"
label variable shb12a   "30 minutes prior to BP measure: eaten"
label variable shb12b   "30 minutes prior to BP measure: had coffee, tea"
label variable shb12c   "30 minutes prior to BP measure: smoked any tobacco product"
label variable shb12d   "30 minutes prior to BP measure: use any other type of tobacco"
label variable shb13    "Arm circumference"
label variable shb14    "Blood pressure monitor cuff size"
label variable shb15h   "Time of first BP reading: hour"
label variable shb15m   "Time of first BP reading: minutes"
label variable shb16s   "First SYSTOLIC reading"
label variable shb16d   "First DIASTOLIC reading"
label variable shb17    "Blood pressure ever been checked previously"
label variable shb18    "Told had high BP on two or more occasions by doctor or other health professional"
label variable shb19    "Currently taking a prescribed medicine to lower BP"
label variable shb22h   "Time of second BP reading: hour"
label variable shb22m   "Time of second BP reading: minutes"
label variable shb23s   "Second SYSTOLIC reading"
label variable shb23d   "Second DIASTOLIC reading"
label variable shb26h   "Time of third BP reading: hour"
label variable shb26m   "Time of third BP reading: minutes"
label variable shb27s   "Third SYSTOLIC reading"
label variable shb27d   "Third DIASTOLIC reading"
label variable shb51    "Time since last ate"
label variable shb52    "Time since last drank, something other than plain water"
label variable shb69h   "Time of blood glucose reading: hour"
label variable shb69m   "Time of blood glucose reading: minutes"
label variable shb70    "Glucose level"
label variable shbsel   "Biomarker Unit selection"
label variable sh21     "Main reason not attending school"
label variable shb10    "Read consent statement - blood pressure"
label variable shb20    "Read consent statement - blood glucose"
label variable ha0      "Index to Household Schedule"
label variable ha1      "Woman's age in years"
label variable ha2      "Woman's weight in kilograms (1 decimal)"
label variable ha3      "Woman's height in centimeters (1 decimal)"
label variable ha4      "Height/Age percentile"
label variable ha5      "Height/Age standard deviation"
label variable ha6      "Height/Age percent ref. median"
label variable ha11     "Weight/Height standard deviation (DHS)"
label variable ha12     "Weight/Height percent ref. median (DHS)"
label variable ha12a    "Weight/Height percent ref. median (Fog)"
label variable ha12b    "Weight/Height percent ref. median (WHO)"
label variable ha13     "Result of measurement - height/weight"
label variable ha32     "Date of birth (CMC)"
label variable ha33     "Completeness of HA32 information"
label variable ha35     "Smoking (cigarettes in last 24 hours)"
label variable ha40     "Body Mass Index"
label variable ha41     "Rohrer's index"
label variable ha50     "Under age 18"
label variable ha51     "Line number of parent/caretaker"
label variable ha52     "Read consent statement - hemoglobin"
label variable ha53     "Hemoglobin level (g/dl - 1 decimal)"
label variable ha54     "Currently pregnant"
label variable ha55     "Result of measurement - hemoglobin"
label variable ha56     "Hemoglobin level adjusted for altitude and smoking (g/dl - 1 decimal)"
label variable ha57     "Anemia level"
label variable ha58     "NA - Agrees to referral - anemia"
label variable ha60     "Marital status"
label variable ha61     "Read consent statement - HIV"
label variable ha62     "Bar code for HIV blood sample"
label variable ha63     "Result of measurement - HIV"
label variable ha64     "Consent for additional tests"
label variable ha65     "Result of woman's individual interview"
label variable ha66     "Woman's highest educational level"
label variable ha67     "Woman's highest year of education"
label variable ha68     "Woman's highest educational level (for preliminary and final report)"
label variable ha69     "HIV weight (6 decimals)"
label variable ha70     "NA - Interviewer that took blood for HIV testing"
label variable hc0      "Index to Household Schedule"
label variable hc1      "Child's age in months"
label variable hc2      "Child's weight in kilograms (1 decimal)"
label variable hc3      "Child's height in centimeters (1 decimal)"
label variable hc4      "Height/Age percentile"
label variable hc5      "Height/Age standard deviation"
label variable hc6      "Height/Age percent of ref. median"
label variable hc7      "Weight/Age percentile"
label variable hc8      "Weight/Age standard deviation"
label variable hc9      "Weight/Age percent of ref. median"
label variable hc10     "Weight/Height percentile"
label variable hc11     "Weight/Height standard deviation"
label variable hc12     "Weight/Height percent of ref. median"
label variable hc13     "Result of measurement - height/weight"
label variable hc15     "Height: lying or standing"
label variable hc16     "Day of birth"
label variable hc17     "Date measured (day)"
label variable hc18     "Date measured (month)"
label variable hc19     "Date measured (year)"
label variable hc27     "Sex"
label variable hc30     "Month of birth"
label variable hc31     "Year of birth"
label variable hc32     "Date of birth (CMC)"
label variable hc33     "Completeness of HC32 information"
label variable hc51     "Line number of parent/caretaker"
label variable hc52     "Read consent statement - hemoglobin"
label variable hc53     "Hemoglobin level (g/dl - 1 decimal)"
label variable hc55     "Result of measurement - hemoglobin"
label variable hc56     "Hemoglobin level adjusted for altitude (g/dl - 1 decimal)"
label variable hc57     "Anemia level"
label variable hc58     "NA - Agrees to referral - anemia"
label variable hc60     "Mother's line number (woman's questionnaire)"
label variable hc61     "Mother's highest educational level"
label variable hc62     "Mother's highest year of education"
label variable hc63     "Preceding birth interval (months)"
label variable hc64     "Birth order number"
label variable hc68     "Mother's highest educational level (for preliminary and final report)"
label variable hc70     "Height/Age standard deviation (new WHO)"
label variable hc71     "Weight/Age standard deviation (new WHO)"
label variable hc72     "Weight/Height standard deviation (new WHO)"
label variable hc73     "BMI standard deviation (new WHO)"
label variable hb0      "Index to Household Schedule"
label variable hb1      "Man's age in years"
label variable hb2      "Man's weight in kilograms (1 decimal)"
label variable hb3      "Man's height in centimeters (1 decimal)"
label variable hb4      "Height/Age percentile"
label variable hb5      "Height/Age standard deviation"
label variable hb6      "Height/Age percent ref. median"
label variable hb11     "Weight/Height standard deviation (DHS)"
label variable hb12     "Weight/Height percent ref. median (DHS)"
label variable hb12a    "Weight/Height percent ref. median (Fog)"
label variable hb12b    "Weight/Height percent ref. median (WHO)"
label variable hb13     "Result of measurement - height/weight"
label variable hb32     "Date of birth (CMC)"
label variable hb33     "Completeness of HB32 information"
label variable hb35     "Smoking (cigarettes in last 24 hours)"
label variable hb40     "Body Mass Index"
label variable hb41     "Rohrer's index"
label variable hb50     "Under age 18"
label variable hb51     "Line number of parent/caretaker"
label variable hb52     "Read consent statement - hemoglobin"
label variable hb53     "Hemoglobin level (g/dl - 1 decimal)"
label variable hb55     "Result of measurement - hemoglobin"
label variable hb56     "Hemoglobin level adjusted for altitude and smoking (g/dl - 1 decimal)"
label variable hb57     "Anemia level"
label variable hb58     "NA - Agrees to referral - anemia"
label variable hb60     "Marital status"
label variable hb61     "Read consent statement - HIV"
label variable hb62     "Bar code for HIV blood sample"
label variable hb63     "Result of measurement - HIV"
label variable hb64     "Consent for additional tests"
label variable hb65     "Result of man's individual interview"
label variable hb66     "Man's highest educational level"
label variable hb67     "Man's highest year of education"
label variable hb68     "Man's highest educational level (for preliminary and final report)"
label variable hb69     "HIV weight (6 decimals)"
label variable hb70     "NA - Interviewer that took blood for HIV testing"
label variable hmlidx   "Mosquito Bed Net Designation Number"
label variable hml3     "NA - Net observed by interviewer"
label variable hml4     "NA - Months ago net obtained"
label variable hml5     "NA - Net treated with insecticide when bought"
label variable hml6     "Net treatment status"
label variable hml7     "Brand of net"
label variable hml8     "NA - Net treated since receiving"
label variable hml9     "NA - Time since last re-treatment (months)"
label variable hml10    "NA - Insecticide-Treated Net (ITN)"
label variable hml11    "Number of persons who slept under this net"
label variable hml21    "Someone slept under this net last night"
label variable hmla     "Line number of person who slept in this net"
label variable hmlb     "Line number of person who slept in this net"
label variable hmlc     "Line number of person who slept in this net"
label variable hmld     "Line number of person who slept in this net"
label variable hmle     "NA - Line number of person who slept in this net"
label variable hmhidx   "Index to Household Schedule"
label variable hml12    "Type of Mosquito Bed Net(s) person slept under last night"
label variable hml13    "Net Designation Number (HMLIDX) for 1st net person slept under last night"
label variable hml14    "Net Designation Number (HMLIDX) for 2nd net person slept under last night"
label variable hml15    "Net Designation Number (HMLIDX) for 3rd net person slept under last night"
label variable hml16    "Corrected age from Individual file"
label variable hml16a   "NA - Age in months (for children)"
label variable hml17    "Flag for age from Individual file"
label variable hml18    "Pregnancy status from Individual file"
label variable hml19    "Person slept under an ever-treated net"
label variable hml20    "Person slept under an LLIN net"
label variable hml30    "NA - Line number of parent/caretaker (for malaria testing)"
label variable hml31    "NA - Read consent statement for malaria"
label variable hml32    "NA - Final result of malaria from blood smear test"
label variable hml32a   "NA - Presence of species: falciparum (Pf)"
label variable hml32b   "NA - Presence of species: malariae (Pm)"
label variable hml32c   "NA - Presence of species: ovale (Po)"
label variable hml32d   "NA - Presence of species: vivax (Pv)"
label variable hml32e   "NA - Presence of species: CS"
label variable hml32f   "NA - Presence of species: CS"
label variable hml32g   "NA - Presence of species: CS"
label variable hml33    "NA - Result of malaria measurement"
label variable hml34    "Bar code for blood smear sample"
label variable hml35    "NA - Result of malaria rapid test"

#delimit ;
label define HV003   
     0 "Incomplete household"
;
label define HV015   
     1 "Completed"
     2 "No Household member/no competent member at home"
     3 "Entire Household absent for extended period of time"
     4 "Postponed"
     5 "Refused"
     6 "Dwelling vacant or address not a dwelling"
     7 "Dwelling destroyed"
     8 "Dwelling not found"
     9 "Other"
;
label define HV017   
     9 "Missing"
;
label define HV018   
   999 "Missing"
;
label define HV020   
     0 "All woman sample"
     1 "Ever married sample"
;
label define HV024   
     1 "Andaman and Nicobar Islands"
     2 "Andhra Pradesh"
     3 "Arunachal Pradesh"
     4 "Assam"
     5 "Bihar"
     6 "Chandigarh"
     7 "Chhattisgarh"
     8 "Dadra and Nagar Haveli"
     9 "Daman and Diu"
    10 "Goa"
    11 "Gujarat"
    12 "Haryana"
    13 "Himachal Pradesh"
    14 "Jammu and Kashmir"
    15 "Jharkhand"
    16 "Karnataka"
    17 "Kerala"
    18 "Lakshadweep"
    19 "Madhya Pradesh"
    20 "Maharashtra"
    21 "Manipur"
    22 "Meghalaya"
    23 "Mizoram"
    24 "Nagaland"
    25 "Delhi"
    26 "Odisha"
    27 "Puducherry"
    28 "Punjab"
    29 "Rajasthan"
    30 "Sikkim"
    31 "Tamil Nadu"
    32 "Tripura"
    33 "Uttar Pradesh"
    34 "Uttarakhand"
    35 "West Bengal"
    36 "Telangana"
;
label define HV025   
     1 "Urban"
     2 "Rural"
;
label define HV026   
     0 "Capital, large city"
     1 "Small city"
     2 "Town"
     3 "Countryside"
;
label define HV027   
     0 "Not selected"
     1 "Men's survey"
     2 "Husband's survey"
;
label define HV030   
   999 "Missing"
;
label define HV040   
  9999 "Missing"
;
label define HV042   
     0 "Not selected"
     1 "Selected"
;
label define HV044   
     0 "Household not selected"
     1 "Household selected"
;
label define HV201   
    10 "PIPED WATER"
    11 "Piped into dwelling"
    12 "Piped to yard/plot"
    13 "Public tap/standpipe"
    20 "TUBE WELL WATER"
    21 "Tube well or borehole"
    30 "DUG WELL (OPEN/PROTECTED)"
    31 "Protected well"
    32 "Unprotected well"
    40 "SURFACE WATER"
    41 "Protected spring"
    42 "Unprotected spring"
    43 "River/dam/lake/ponds/stream/canal/irrigation channel"
    51 "Rainwater"
    61 "Tanker truck"
    62 "Cart with small tank"
    71 "Bottled water"
    72 "Community RO Plant"
    96 "Other"
;
label define HV202   
    10 "PIPED WATER"
    11 "Piped into dwelling"
    12 "Piped to yard/plot"
    13 "Public tap/standpipe"
    20 "TUBE WELL WATER"
    21 "Tube well or borehole"
    30 "DUG WELL (OPEN/PROTECTED)"
    31 "Protected well"
    32 "Unprotected well"
    40 "SURFACE WATER"
    41 "Protected spring"
    42 "Unprotected spring"
    43 "River/dam/lake/ponds/stream/canal/irrigation channel"
    51 "Rainwater"
    61 "Tanker truck"
    62 "Cart with small tank"
    71 "Bottled water"
    96 "Other"
;
label define HV204   
     0 "Delivered to dwelling"
   996 "On premises"
   998 "Don't know"
;
label define HV205   
    10 "FLUSH TOILET"
    11 "Flush to piped sewer system"
    12 "Flush to septic tank"
    13 "Flush to pit latrine"
    14 "Flush to somewhere else"
    15 "Flush, don't know where"
    20 "PIT TOILET LATRINE"
    21 "Ventilated Improved Pit latrine (VIP)"
    22 "Pit latrine with slab"
    23 "Pit latrine without slab/open pit"
    30 "NO FACILITY"
    31 "No facility/bush/field"
    41 "Composting toilet"
    44 "Dry toilet"
    96 "Other"
;
label define HV206   
     0 "No"
     1 "Yes"
;
label define HV207   
     0 "No"
     1 "Yes"
;
label define HV208   
     0 "No"
     1 "Yes"
;
label define HV209   
     0 "No"
     1 "Yes"
;
label define HV210   
     0 "No"
     1 "Yes"
;
label define HV211   
     0 "No"
     1 "Yes"
;
label define HV212   
     0 "No"
     1 "Yes"
;
label define HV213   
    10 "NATURAL"
    11 "Mud/clay/earth"
    12 "Sand"
    13 "Dung"
    20 "RUDIMENTARY"
    21 "Raw wood planks"
    22 "Palm, bamboo"
    23 "Brick"
    24 "Stone"
    30 "FINISHED"
    31 "Parquet, polished wood"
    32 "Vinyl, asphalt strips"
    33 "Ceramic tiles"
    34 "Cement"
    35 "Carpet"
    36 "Polished stone/marble/granite"
    96 "other"
;
label define HV214   
    10 "NATURAL"
    11 "No walls"
    12 "Cane/palm/trunks"
    13 "Mud"
    14 "Grass/reeds/thatch"
    20 "RUDIMENTARY"
    21 "Bamboo with mud"
    22 "Stone with mud"
    23 "Plywood"
    24 "Cardboard"
    25 "Unburnt brick"
    26 "Raw/reused wood"
    30 "FINISHED"
    31 "Cement/concrete"
    32 "Stone with lime/cement"
    33 "Burnt bricks"
    34 "Cement blocks"
    35 "Wood planks/shingles"
    36 "GI/metal/asbestos sheets"
    96 "other"
;
label define HV215   
    10 "NATURAL"
    11 "No roof"
    12 "Thatch/palm leaf"
    13 "Mud"
    14 "Sod/mud and grass mixture"
    15 "Plastic/polythene sheeting"
    20 "RUDIMENTARY"
    21 "Rustic mat"
    22 "Palm/bamboo"
    23 "Raw wood planks/timber"
    24 "Unburnt bricks"
    25 "Loosely packed stone"
    30 "FINISHED"
    31 "Metal/GI"
    32 "Wood"
    33 "Calamine/cement fibre"
    34 "Asbestos sheets"
    35 "RCC/RBC/cement/concrete"
    36 "Roofing shingles"
    37 "Tiles"
    38 "Slate"
    39 "Burnt brick"
    96 "other"
;
label define HV216   
    25 "25 or more rooms"
;
label define HV217   
     0 "No adults"
     1 "One adult"
     2 "Two adults, opposite sex"
     3 "Two adults, same sex"
     4 "Three+ related adults"
     5 "Unrelated adults"
;
label define HV219   
     1 "Male"
     2 "Female"
;
label define HV220   
    97 "97+"
    98 "Don't know"
;
label define HV221   
     0 "No"
     1 "Yes"
;
label define HV225   
     0 "No"
     1 "Yes"
;
label define HV226   
     1 "Electricity"
     2 "LPG, natural gas"
     4 "Biogas"
     5 "Kerosene"
     6 "Coal, lignite"
     7 "Charcoal"
     8 "Wood"
     9 "Straw/shrubs/grass"
    10 "Agricultural crop"
    11 "Animal dung"
    95 "No food cooked in house"
    96 "Other"
;
label define HV227   
     0 "No"
     1 "Yes"
;
label define HV228   
     0 "No"
     1 "All children"
     2 "Some children"
     3 "No net in household"
;
label define HV230A  
     1 "Observed"
     2 "Not observed: not in dwelling"
     3 "Not observed: no permission to see"
     4 "Not observed: other reason"
;
label define HV230B  
     0 "Water not available"
     1 "Water is available"
;
label define HV232   
     0 "No"
     1 "Yes"
;
label define HV232B  
     0 "No"
     1 "Yes"
;
label define HV232C  
     0 "No"
     1 "Yes"
;
label define HV232D  
     0 "No"
     1 "Yes"
;
label define HV232E  
     0 "No"
     1 "Yes"
;
label define HV232Y  
     0 "No"
     1 "Yes: no cleansing agent observed"
;
label define HV234   
     0 "0 PPM (no iodine)"
     7 "Below 15 PPM"
    15 "15 PPM and above"
    30 "30 PPM"
   994 "Salt not tested"
   995 "No salt in household"
;
label define HV234A  
     0 "No iodine"
     1 "Iodine present"
     3 "No salt in household"
     6 "Salt not tested"
;
label define HV235   
     1 "In own dwelling"
     2 "In own yard/plot"
     3 "Elsewhere"
;
label define HV236   
     1 "Adult woman"
     2 "Adult man"
     3 "Female child under 15 years old"
     4 "Male child under 15 years old"
     6 "Other"
;
label define HV237   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV237A  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV237B  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV237C  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV237D  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV237E  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV237F  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV237G  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV237H  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV237I  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV237J  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV237K  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV237X  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV237Z  
     0 "No"
     1 "Yes: don't know what is done to water"
     8 "Don't know"
;
label define HV238   
    95 "10 or more households"
    98 "Don't know"
;
label define HV239   
     1 "Open fire (including Chullah)"
     2 "Stove"
     6 "Other"
;
label define HV240   
     0 "Neither chimney or hood"
     1 "Chimney"
     2 "Hood"
;
label define HV241   
     1 "In the house"
     2 "In a separate building"
     3 "Outdoors"
     6 "Other"
;
label define HV242   
     0 "No"
     1 "Yes"
;
label define HV243A  
     0 "No"
     1 "Yes"
;
label define HV243B  
     0 "No"
     1 "Yes"
;
label define HV243C  
     0 "No"
     1 "Yes"
;
label define HV243D  
     0 "No"
     1 "Yes"
;
label define HV244   
     0 "No"
     1 "Yes"
;
label define HV245   
     0 "Less than 0.1 hectares"
   950 "95.0 hectares or more"
   998 "Unknown"
;
label define HV246   
     0 "No"
     1 "Yes"
;
label define HV246A  
     0 "None"
    95 "95 or more"
    98 "Unknown"
;
label define HV246B  
     0 "None"
    95 "95 or more"
    98 "Unknown"
;
label define HV246C  
     0 "None"
    95 "95 or more"
    98 "Unknown"
;
label define HV246D  
     0 "None"
    95 "95 or more"
    98 "Unknown"
;
label define HV246E  
     0 "None"
    95 "95 or more"
    98 "Unknown"
;
label define HV246F  
     0 "None"
    95 "95 or more"
    98 "Unknown"
;
label define HV246G  
     0 "None"
    95 "95 or more"
    98 "Unknown"
;
label define HV246H  
     0 "None"
    95 "95 or more"
    98 "Unknown"
;
label define HV246I  
     0 "None"
    95 "95 or more"
    98 "Unknown"
;
label define HV246J  
     0 "None"
    95 "95 or more"
    98 "Unknown"
;
label define HV246K  
     0 "None"
    95 "95 or more"
    98 "Unknown"
;
label define HV247   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV252   
     0 "Never"
     1 "Daily"
     2 "Weekly"
     3 "Monthly"
     4 "Less than monthly"
;
label define HV253   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV253A  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV253B  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV253C  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV253D  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV253E  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV253F  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV253G  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV253H  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV253X  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV253Z  
     0 "No"
     1 "Yes: don't know who sprayed the dwelling"
     8 "Don't know if it was sprayed"
;
label define HV270   
     1 "Poorest"
     2 "Poorer"
     3 "Middle"
     4 "Richer"
     5 "Richest"
;
label define HML1    
    98 "Don't know"
;
label define HML2    
    99 "Missing"
;
label define SHDISTRI
     1 "Kupwara"
     2 "Badgam"
     3 "Leh"
     4 "Kargil"
     5 "Punch"
     6 "Rajouri"
     7 "Kathua"
     8 "Baramula"
     9 "Bandipore"
    10 "Srinagar"
    11 "Ganderbal"
    12 "Pulwama"
    13 "Shupiyan"
    14 "Anantnag"
    15 "Kulgam"
    16 "Doda"
    17 "Ramban"
    18 "Kishtwar"
    19 "Udhampur"
    20 "Reasi"
    21 "Jammu"
    22 "Samba"
    23 "Chamba"
    24 "Kangra"
    25 "Lahul and Spiti"
    26 "Kullu"
    27 "Mandi"
    28 "Hamirpur"
    29 "Una"
    30 "Bilaspur"
    31 "Solan"
    32 "Sirmaur"
    33 "Shimla"
    34 "Kinnaur"
    35 "Gurdaspur"
    36 "Kapurthala"
    37 "Jalandhar"
    38 "Hoshiarpur"
    39 "Sangrur"
    40 "Fatehgarh Sahib"
    41 "Ludhiana"
    42 "Moga"
    43 "Firozpur"
    44 "Muktsar"
    45 "Faridkot"
    46 "Bathinda"
    47 "Mansa"
    48 "Patiala"
    49 "Amritsar"
    50 "Tarn Taran"
    51 "Rupnagar"
    52 "Sahibzada Ajit Singh Nagar"
    53 "Shahid Bhagat Singh Nagar"
    54 "Barnala"
    55 "Chandigarh"
    56 "Uttarkashi"
    57 "Chamoli"
    58 "Rudraprayag"
    59 "Tehri Garhwal"
    60 "Dehradun"
    61 "Garhwal"
    62 "Pithoragarh"
    63 "Bageshwar"
    64 "Almora"
    65 "Champawat"
    66 "Nainital"
    67 "Udham Singh Nagar"
    68 "Hardwar"
    69 "Panchkula"
    70 "Ambala"
    71 "Yamunanagar"
    72 "Kurukshetra"
    73 "Kaithal"
    74 "Karnal"
    75 "Panipat"
    76 "Sonipat"
    77 "Jind"
    78 "Fatehabad"
    79 "Sirsa"
    80 "Hisar"
    81 "Bhiwani"
    82 "Rohtak"
    83 "Jhajjar"
    84 "Mahendragarh"
    85 "Rewari"
    86 "Gurgaon"
    87 "Mewat"
    88 "Faridabad"
    89 "Palwal"
    90 "North West"
    91 "North"
    92 "North East"
    93 "East"
    94 "New Delhi"
    95 "Central"
    96 "West"
    97 "South West"
    98 "South"
    99 "Ganganagar"
   100 "Hanumangarh"
   101 "Bikaner"
   102 "Churu"
   103 "Jhunjhunun"
   104 "Alwar"
   105 "Bharatpur"
   106 "Dhaulpur"
   107 "Karauli"
   108 "Sawai Madhopur"
   109 "Dausa"
   110 "Jaipur"
   111 "Sikar"
   112 "Nagaur"
   113 "Jodhpur"
   114 "Jaisalmer"
   115 "Barmer"
   116 "Jalor"
   117 "Sirohi"
   118 "Pali"
   119 "Ajmer"
   120 "Tonk"
   121 "Bundi"
   122 "Bhilwara"
   123 "Rajsamand"
   124 "Dungarpur"
   125 "Banswara"
   126 "Chittaurgarh"
   127 "Kota"
   128 "Baran"
   129 "Jhalawar"
   130 "Udaipur"
   131 "Pratapgarh"
   132 "Saharanpur"
   133 "Muzaffarnagar"
   134 "Bijnor"
   135 "Moradabad"
   136 "Rampur"
   137 "Jyotiba Phule Nagar"
   138 "Meerut"
   139 "Baghpat"
   140 "Ghaziabad"
   141 "Gautam Buddha Nagar"
   142 "Bulandshahr"
   143 "Aligarh"
   144 "Mahamaya Nagar"
   145 "Mathura"
   146 "Agra"
   147 "Firozabad"
   148 "Mainpuri"
   149 "Budaun"
   150 "Bareilly"
   151 "Pilibhit"
   152 "Shahjahanpur"
   153 "Kheri"
   154 "Sitapur"
   155 "Hardoi"
   156 "Unnao"
   157 "Lucknow"
   158 "Rae Bareli"
   159 "Farrukhabad"
   160 "Kannauj"
   161 "Etawah"
   162 "Auraiya"
   163 "Kanpur Dehat"
   164 "Kanpur Nagar"
   165 "Jalaun"
   166 "Jhansi"
   167 "Lalitpur"
   168 "Hamirpur"
   169 "Mahoba"
   170 "Banda"
   171 "Chitrakoot"
   172 "Fatehpur"
   173 "Pratapgarh"
   174 "Kaushambi"
   175 "Allahabad"
   176 "Bara Banki"
   177 "Faizabad"
   178 "Ambedkar Nagar"
   179 "Sultanpur"
   180 "Bahraich"
   181 "Shrawasti"
   182 "Balrampur"
   183 "Gonda"
   184 "Siddharth Nagar"
   185 "Basti"
   186 "Sant Kabir Nagar"
   187 "Mahrajganj"
   188 "Gorakhpur"
   189 "Kushinagar"
   190 "Deoria"
   191 "Azamgarh"
   192 "Mau"
   193 "Ballia"
   194 "Jaunpur"
   195 "Ghazipur"
   196 "Chandauli"
   197 "Varanasi"
   198 "Sant Ravidas Nagar (Bhadohi)"
   199 "Mirzapur"
   200 "Sonbhadra"
   201 "Etah"
   202 "Kanshiram Nagar"
   203 "Pashchim Champaran"
   204 "Purba Champaran"
   205 "Sheohar"
   206 "Sitamarhi"
   207 "Madhubani"
   208 "Supaul"
   209 "Araria"
   210 "Kishanganj"
   211 "Purnia"
   212 "Katihar"
   213 "Madhepura"
   214 "Saharsa"
   215 "Darbhanga"
   216 "Muzaffarpur"
   217 "Gopalganj"
   218 "Siwan"
   219 "Saran"
   220 "Vaishali"
   221 "Samastipur"
   222 "Begusarai"
   223 "Khagaria"
   224 "Bhagalpur"
   225 "Banka"
   226 "Munger"
   227 "Lakhisarai"
   228 "Sheikhpura"
   229 "Nalanda"
   230 "Patna"
   231 "Bhojpur"
   232 "Buxar"
   233 "Kaimur (Bhabua)"
   234 "Rohtas"
   235 "Aurangabad"
   236 "Gaya"
   237 "Nawada"
   238 "Jamui"
   239 "Jehanabad"
   240 "Arwal"
   241 "North  District"
   242 "West District"
   243 "South District"
   244 "East District"
   245 "Tawang"
   246 "West Kameng"
   247 "East Kameng"
   248 "Papumpare"
   249 "Upper Subansiri"
   250 "West Siang"
   251 "East Siang"
   252 "Upper Siang"
   253 "Changlang"
   254 "Tirap"
   255 "Lower Subansiri"
   256 "Kurung Kumey"
   257 "Dibang Valley"
   258 "Lower Dibang Valley"
   259 "Lohit"
   260 "Anjaw"
   261 "Mon"
   262 "Mokokchung"
   263 "Zunheboto"
   264 "Wokha"
   265 "Dimapur"
   266 "Phek"
   267 "Tuensang"
   268 "Longleng"
   269 "Kiphire"
   270 "Kohima"
   271 "Peren"
   272 "Senapati (Excluding 3 Sub-Divisions)"
   273 "Tamenglong"
   274 "Churachandpur"
   275 "Bishnupur"
   276 "Thoubal"
   277 "Imphal West"
   278 "Imphal East"
   279 "Ukhrul"
   280 "Chandel"
   281 "Mamit"
   282 "Kolasib"
   283 "Aizawl"
   284 "Champhai"
   285 "Serchhip"
   286 "Lunglei"
   287 "Lawngtlai"
   288 "Saiha"
   289 "West Tripura"
   290 "South Tripura"
   291 "Dhalai"
   292 "North Tripura"
   293 "West Garo Hills"
   294 "East Garo Hills"
   295 "South Garo Hills"
   296 "West Khasi Hills"
   297 "Ribhoi"
   298 "East Khasi Hills"
   299 "Jaintia Hills"
   300 "Kokrajhar"
   301 "Dhubri"
   302 "Goalpara"
   303 "Barpeta"
   304 "Morigaon"
   305 "Nagaon"
   306 "Sonitpur"
   307 "Lakhimpur"
   308 "Dhemaji"
   309 "Tinsukia"
   310 "Dibrugarh"
   311 "Sivasagar"
   312 "Jorhat"
   313 "Golaghat"
   314 "Karbi Anglong"
   315 "Dima Hasao"
   316 "Cachar"
   317 "Karimganj"
   318 "Hailakandi"
   319 "Bongaigaon"
   320 "Chirang"
   321 "Kamrup"
   322 "Kamrup Metropolitan"
   323 "Nalbari"
   324 "Baksa"
   325 "Darrang"
   326 "Udalguri"
   327 "Darjiling"
   328 "Jalpaiguri"
   329 "Koch Bihar"
   330 "Uttar Dinajpur"
   331 "Dakshin Dinajpur"
   332 "Maldah"
   333 "Murshidabad"
   334 "Birbhum"
   335 "Barddhaman"
   336 "Nadia"
   337 "North Twenty Four Parganas"
   338 "Hugli"
   339 "Bankura"
   340 "Puruliya"
   341 "Haora"
   342 "Kolkata"
   343 "South Twenty Four Parganas"
   344 "Paschim Medinipur"
   345 "Purba Medinipur"
   346 "Garhwa"
   347 "Chatra"
   348 "Kodarma"
   349 "Giridih"
   350 "Deoghar"
   351 "Godda"
   352 "Sahibganj"
   353 "Pakur"
   354 "Dhanbad"
   355 "Bokaro"
   356 "Lohardaga"
   357 "Purbi Singhbhum"
   358 "Palamu"
   359 "Latehar"
   360 "Hazaribagh"
   361 "Ramgarh"
   362 "Dumka"
   363 "Jamtara"
   364 "Ranchi"
   365 "Khunti"
   366 "Gumla"
   367 "Simdega"
   368 "Pashchimi Singhbhum"
   369 "Saraikela Kharsawan"
   370 "Bargarh"
   371 "Jharsuguda"
   372 "Sambalpur"
   373 "Debagarh"
   374 "Sundargarh"
   375 "Kendujhar"
   376 "Mayurbhanj"
   377 "Baleshwar"
   378 "Bhadrak"
   379 "Kendrapara"
   380 "Jagatsinghapur"
   381 "Cuttack"
   382 "Jajapur"
   383 "Dhenkanal"
   384 "Anugul"
   385 "Nayagarh"
   386 "Khordha"
   387 "Puri"
   388 "Ganjam"
   389 "Gajapati"
   390 "Kandhamal"
   391 "Baudh"
   392 "Subarnapur"
   393 "Balangir"
   394 "Nuapada"
   395 "Kalahandi"
   396 "Rayagada"
   397 "Nabarangapur"
   398 "Koraput"
   399 "Malkangiri"
   400 "Korea (Koriya)"
   401 "Surguja"
   402 "Jashpur"
   403 "Raigarh"
   404 "Korba"
   405 "Janjgir - Champa"
   406 "Bilaspur"
   407 "Kabirdham"
   408 "Rajnandgaon"
   409 "Durg"
   410 "Raipur"
   411 "Mahasamund"
   412 "Dhamtari"
   413 "Uttar Bastar Kanker"
   414 "Bastar"
   415 "Narayanpur"
   416 "Dakshin Bastar Dantewada"
   417 "Bijapur"
   418 "Sheopur"
   419 "Morena"
   420 "Bhind"
   421 "Gwalior"
   422 "Datia"
   423 "Shivpuri"
   424 "Tikamgarh"
   425 "Chhatarpur"
   426 "Panna"
   427 "Sagar"
   428 "Damoh"
   429 "Satna"
   430 "Rewa"
   431 "Umaria"
   432 "Neemuch"
   433 "Mandsaur"
   434 "Ratlam"
   435 "Ujjain"
   436 "Shajapur"
   437 "Dewas"
   438 "Dhar"
   439 "Indore"
   440 "Khargone (West Nimar)"
   441 "Barwani"
   442 "Rajgarh"
   443 "Vidisha"
   444 "Bhopal"
   445 "Sehore"
   446 "Raisen"
   447 "Betul"
   448 "Harda"
   449 "Hoshangabad"
   450 "Katni"
   451 "Jabalpur"
   452 "Narsimhapur"
   453 "Dindori"
   454 "Mandla"
   455 "Chhindwara"
   456 "Seoni"
   457 "Balaghat"
   458 "Guna"
   459 "Ashoknagar"
   460 "Shahdol"
   461 "Anuppur"
   462 "Sidhi"
   463 "Singrauli"
   464 "Jhabua"
   465 "Alirajpur"
   466 "Khandwa (East Nimar)"
   467 "Burhanpur"
   468 "Kachchh"
   469 "Banaskantha"
   470 "Patan"
   471 "Mahesana"
   472 "Sabarkantha"
   473 "Gandhinagar"
   474 "Ahmadabad"
   475 "Surendranagar"
   476 "Rajkot"
   477 "Jamnagar"
   478 "Porbandar"
   479 "Junagadh"
   480 "Amreli"
   481 "Bhavnagar"
   482 "Anand"
   483 "Kheda"
   484 "Panchmahal"
   485 "Dohad"
   486 "Vadodara"
   487 "Narmada"
   488 "Bharuch"
   489 "The Dangs"
   490 "Navsari"
   491 "Valsad"
   492 "Surat"
   493 "Tapi"
   494 "Diu"
   495 "Daman"
   496 "Dadra & Nagar Haveli"
   497 "Nandurbar"
   498 "Dhule"
   499 "Jalgaon"
   500 "Buldana"
   501 "Akola"
   502 "Washim"
   503 "Amravati"
   504 "Wardha"
   505 "Nagpur"
   506 "Bhandara"
   507 "Gondiya"
   508 "Gadchiroli"
   509 "Chandrapur"
   510 "Yavatmal"
   511 "Nanded"
   512 "Hingoli"
   513 "Parbhani"
   514 "Jalna"
   515 "Aurangabad"
   516 "Nashik"
   517 "Thane"
   518 "Mumbai Suburban"
   519 "Mumbai"
   520 "Raigarh"
   521 "Pune"
   522 "Ahmadnagar"
   523 "Bid"
   524 "Latur"
   525 "Osmanabad"
   526 "Solapur"
   527 "Satara"
   528 "Ratnagiri"
   529 "Sindhudurg"
   530 "Kolhapur"
   531 "Sangli"
   532 "Adilabad"
   533 "Nizamabad"
   534 "Karimnagar"
   535 "Medak"
   536 "Hyderabad"
   537 "Rangareddy"
   538 "Mahbubnagar"
   539 "Nalgonda"
   540 "Warangal"
   541 "Khammam"
   542 "Srikakulam"
   543 "Vizianagaram"
   544 "Visakhapatnam"
   545 "East Godavari"
   546 "West Godavari"
   547 "Krishna"
   548 "Guntur"
   549 "Prakasam"
   550 "Sri Potti Sriramulu Nellore"
   551 "Y.S.R."
   552 "Kurnool"
   553 "Anantapur"
   554 "Chittoor"
   555 "Belgaum"
   556 "Bagalkot"
   557 "Bijapur"
   558 "Bidar"
   559 "Raichur"
   560 "Koppal"
   561 "Gadag"
   562 "Dharwad"
   563 "Uttara Kannada"
   564 "Haveri"
   565 "Bellary"
   566 "Chitradurga"
   567 "Davanagere"
   568 "Shimoga"
   569 "Udupi"
   570 "Chikmagalur"
   571 "Tumkur"
   572 "Bangalore"
   573 "Mandya"
   574 "Hassan"
   575 "Dakshina Kannada"
   576 "Kodagu"
   577 "Mysore"
   578 "Chamarajanagar"
   579 "Gulbarga"
   580 "Yadgir"
   581 "Kolar"
   582 "Chikkaballapura"
   583 "Bangalore Rural"
   584 "Ramanagara"
   585 "North Goa"
   586 "South Goa"
   587 "Lakshadweep"
   588 "Kasaragod"
   589 "Kannur"
   590 "Wayanad"
   591 "Kozhikode"
   592 "Malappuram"
   593 "Palakkad"
   594 "Thrissur"
   595 "Ernakulam"
   596 "Idukki"
   597 "Kottayam"
   598 "Alappuzha"
   599 "Pathanamthitta"
   600 "Kollam"
   601 "Thiruvananthapuram"
   602 "Thiruvallur"
   603 "Chennai"
   604 "Kancheepuram"
   605 "Vellore"
   606 "Tiruvannamalai"
   607 "Viluppuram"
   608 "Salem"
   609 "Namakkal"
   610 "Erode"
   611 "The Nilgiris"
   612 "Dindigul"
   613 "Karur"
   614 "Tiruchirappalli"
   615 "Perambalur"
   616 "Ariyalur"
   617 "Cuddalore"
   618 "Nagapattinam"
   619 "Thiruvarur"
   620 "Thanjavur"
   621 "Pudukkottai"
   622 "Sivaganga"
   623 "Madurai"
   624 "Theni"
   625 "Virudhunagar"
   626 "Ramanathapuram"
   627 "Thoothukkudi"
   628 "Tirunelveli"
   629 "Kanniyakumari"
   630 "Dharmapuri"
   631 "Krishnagiri"
   632 "Coimbatore"
   633 "Tiruppur"
   634 "Yanam"
   635 "Puducherry"
   636 "Mahe"
   637 "Karaikal"
   638 "Nicobars"
   639 "North & Middle Andaman"
   640 "South Andaman"
;
label define SHSLUMC 
     0 "Non-slum"
     1 "Slum"
;
label define SHSLUMO 
     0 "Non-slum"
     1 "Slum"
;
label define SHCONSENT
     0 "Respondent does not agree to be interviewed"
     1 "Respondent agrees to be interviewed"
;
label define SHLANGQ 
     1 "Assamese"
     2 "Bengali"
     3 "Gujarati"
     4 "Hindi"
     5 "Kannada"
     6 "Kashmiri"
     7 "Konkani"
     8 "Malayalam"
     9 "Manipuri"
    10 "Marathi"
    11 "Nepali"
    12 "Oriya"
    13 "Punjabi"
    14 "Sindhi"
    15 "Tamil"
    16 "Telugu"
    17 "Urdu"
    18 "English"
    19 "Garo"
    20 "Khasi"
    21 "Mizoram"
;
label define SHLANGRM
     1 "Assamese"
     2 "Bengali"
     3 "Gujarati"
     4 "Hindi"
     5 "Kannada"
     6 "Kashmiri"
     7 "Konkani"
     8 "Malayalam"
     9 "Manipuri"
    10 "Marathi"
    11 "Nepali"
    12 "Oriya"
    13 "Punjabi"
    14 "Sindhi"
    15 "Tamil"
    16 "Telugu"
    17 "Urdu"
    18 "English"
    19 "Garo"
    20 "Khasi"
    21 "Mizoram"
    96 "Other"
;
label define SHLANGI 
     1 "Assamese"
     2 "Bengali"
     3 "Gujarati"
     4 "Hindi"
     5 "Kannada"
     6 "Kashmiri"
     7 "Konkani"
     8 "Malayalam"
     9 "Manipuri"
    10 "Marathi"
    11 "Nepali"
    12 "Oriya"
    13 "Punjabi"
    14 "Sindhi"
    15 "Tamil"
    16 "Telugu"
    17 "Urdu"
    18 "English"
    19 "Garo"
    20 "Khasi"
    21 "Mizoram"
    96 "Other"
;
label define SHTRANSL
     0 "No"
     1 "Yes"
;
label define SH23    
     0 "No"
     1 "Yes"
;
label define SH34    
     1 "Hindu"
     2 "Muslim"
     3 "Christian"
     4 "Sikh"
     5 "Buddhist/Neo-Buddhist"
     6 "Jain"
     7 "Jewish"
     8 "Parsi/Zoroastrian"
     9 "No religion"
    96 "other"
;
label define SH35    
   991 "Caste"
   992 "Tribe"
   993 "No caste/tribe"
   998 "Don't know"
;
label define SH36    
     1 "Scheduled caste"
     2 "Scheduled tribe"
     3 "Other Backward Class"
     4 "None of above"
     8 "Don't know"
;
label define SH37B   
     0 "No"
     1 "Yes"
;
label define SH37C   
     0 "No"
     1 "Yes"
;
label define SH37D   
     0 "No"
     1 "Yes"
;
label define SH37E   
     0 "No"
     1 "Yes"
;
label define SH37F   
     0 "No"
     1 "Yes"
;
label define SH37G   
     0 "No"
     1 "Yes"
;
label define SH37I   
     0 "No"
     1 "Yes"
;
label define SH37J   
     0 "No"
     1 "Yes"
;
label define SH37K   
     0 "No"
     1 "Yes"
;
label define SH37N   
     0 "No"
     1 "Yes"
;
label define SH37O   
     0 "No"
     1 "Yes"
;
label define SH37Q   
     0 "No"
     1 "Yes"
;
label define SH37R   
     0 "No"
     1 "Yes"
;
label define SH37X   
     0 "No"
     1 "Yes"
;
label define SH37Y   
     0 "No"
     1 "Yes"
;
label define SH37Z   
     0 "No"
     1 "Yes"
;
label define SH46    
     0 "No"
     1 "Yes"
;
label define SH47    
     1 "Male member"
     2 "Female member"
     3 "Both"
     8 "Don't know"
;
label define SH49    
     1 "Male member"
     2 "Female member"
     3 "Both"
     8 "Don't know"
;
label define HV245I  
     0 "Less than 0.1 hectares"
   950 "95.0 hectares or more"
   995 "No irrigated agricultural land"
   998 "Unknown"
;
label define SH52A   
     0 "No"
     1 "Yes"
;
label define SH52B   
     0 "No"
     1 "Yes"
;
label define SH52C   
     0 "No"
     1 "Yes"
;
label define SH52D   
     0 "No"
     1 "Yes"
;
label define SH52E   
     0 "No"
     1 "Yes"
;
label define SH52F   
     0 "No"
     1 "Yes"
;
label define SH54    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define SH55A   
     0 "No"
     1 "ESIS"
;
label define SH55B   
     0 "No"
     1 "CGHS"
;
label define SH55C   
     0 "No"
     1 "State health insurance scheme"
;
label define SH55D   
     0 "No"
     1 "Rashtriya Swasthya Bima Yojana (RSBY)"
;
label define SH55E   
     0 "No"
     1 "Comm Health Insurance Programme"
;
label define SH55F   
     0 "No"
     1 "other health insurance through employer"
;
label define SH55G   
     0 "No"
     1 "Medical reimbursement from employer"
;
label define SH55H   
     0 "No"
     1 "other privately purchased comm health insurance"
;
label define SH55X   
     0 "No"
     1 "other"
;
label define SH56    
    11 "Public: Government/municipal hospital"
    12 "Public: Government dispensary"
    13 "Public: UHC/UHP/UFWC"
    14 "Public: CHC/rural hospital/block PHC"
    15 "Public: PHC/additional PHC"
    16 "Public: Sub-centre"
    17 "Public: Vaidya/hakim/homeopath (AYUSH)"
    18 "Public: ANGANWADI/ICDS centre"
    19 "Public: ASHA"
    20 "Public: Government mobile clinic"
    21 "Other public sector"
    31 "NGO or trust hospital/clinic"
    41 "Private hospital"
    42 "Private doctor/clinic"
    43 "Private paramedic"
    44 "Private: Vaidya/hakim/homeopath (AYUSH)"
    45 "Private: Traditional healer"
    46 "Private: Pharmacy/drugstore"
    47 "Private: DAI (TBA)"
    48 "Other private sector"
    51 "Shop"
    52 "Home treatment"
    96 "Other"
;
label define SH57A   
     0 "No"
     1 "No nearby facility"
;
label define SH57B   
     0 "No"
     1 "Facility timing not convenient"
;
label define SH57C   
     0 "No"
     1 "Health personnel often absent"
;
label define SH57D   
     0 "No"
     1 "Waiting time too long"
;
label define SH57E   
     0 "No"
     1 "Poor quality of care"
;
label define SH57X   
     0 "No"
     1 "other"
;
label define SH58    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define SH61A   
     0 "No"
     1 "Purchased from the market"
;
label define SH61B   
     0 "No"
     1 "Government"
;
label define SH61C   
     0 "No"
     1 "Supplied by NGO/trust"
;
label define SH61X   
     0 "No"
     1 "Other"
;
label define SH61Z   
     0 "No"
     1 "Don't know"
;
label define SH70    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define SH39    
     1 "Stove"
     2 "Chullah"
     3 "Open fire"
     6 "Other"
;
label define SHNFHS2 
     1 "Kachha"
     2 "semi-Pucca"
     3 "Pucca"
;
label define SHSTRUC 
     1 "Nuclear"
     2 "Non-nuclear"
;
label define SH50    
     0 "Less than 0.1 units"
   950 "95.0 units or more"
   998 "Unknown"
;
label define SH51    
     0 "Less than 0.1 units"
   950 "95.0 units or more"
   995 "No irrigated agricultural land"
   998 "Unknown"
;
label define AGLAND  
     1 "No agricultural land"
     3 "Irrigated agricultural land only"
     4 "Non-irrigated agricultural land only"
     5 "Both irrigated and non-irrigated agricultural land"
     6 "Agricultural land, irrigation not determined"
;
label define SV270S  
     1 "Poorest"
     2 "Poorer"
     3 "Middle"
     4 "Richer"
     5 "Richest"
;
label define SV270U  
     1 "Poorest"
     2 "Poorer"
     3 "Middle"
     4 "Richer"
     5 "Richest"
;
label define SV270US 
     1 "Poorest"
     2 "Poorer"
     3 "Middle"
     4 "Richer"
     5 "Richest"
;
label define SV270R  
     1 "Poorest"
     2 "Poorer"
     3 "Middle"
     4 "Richer"
     5 "Richest"
;
label define SV270RS 
     1 "Poorest"
     2 "Poorer"
     3 "Middle"
     4 "Richer"
     5 "Richest"
;
label define SH50U   
     1 "Acres"
     2 "Hectares"
     6 "Other type of measurement"
;
label define SHPHASE 
     1 "Phase 1: 2014-15 school year"
     2 "Phase 2: 2015-16 school year"
;
label define HV101   
     1 "Head"
     2 "Wife or husband"
     3 "Son/daughter"
     4 "Son/daughter-in-law"
     5 "Grandchild"
     6 "Parent"
     7 "Parent-in-law"
     8 "Brother/sister"
    10 "other relative"
    11 "Adopted/foster child"
    12 "Not related"
    15 "Brother-in-law/sister-in-law"
    16 "Niece/nephew"
    17 "Domestic servant"
    98 "Don't know"
;
label define HV102   
     0 "No"
     1 "Yes"
;
label define HV103   
     0 "No"
     1 "Yes"
;
label define HV104   
     1 "Male"
     2 "Female"
;
label define HV105   
    95 "95+"
    98 "Don't know"
;
label define HV106   
     0 "No education, preschool"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "Don't know"
;
label define HV107   
    98 "Don't know"
;
label define HV108   
    97 "Inconsistent"
    98 "Don't know"
;
label define HV109   
     0 "No education"
     1 "Incomplete primary"
     2 "Complete primary"
     3 "Incomplete secondary"
     4 "Complete secondary"
     5 "Higher"
     8 "Don't know"
;
label define HV110   
     0 "No"
     1 "Yes"
;
label define HV111   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV112   
     0 "Mother not in household"
;
label define HV113   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV114   
     0 "Father not in household"
;
label define HV115   
     0 "Never married [includes: married gauna not performed]"
     1 "Married"
     2 "Living together"
     3 "Widowed"
     4 "Divorced"
     5 "Not living together"
     8 "Don't know"
;
label define HV116   
     0 "Never married"
     1 "Currently married"
     2 "Formerly/ever married"
;
label define HV117   
     0 "Not eligible"
     1 "Eligible"
;
label define HV118   
     0 "Not eligible"
     1 "Eligible"
;
label define HV120   
     0 "Not eligible"
     1 "Eligible"
;
label define HV121   
     0 "No"
     1 "Currently attending"
     2 "Attended at some time"
     8 "Don't know"
;
label define HV122   
     0 "No education, preschool"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "Don't know"
;
label define HV123   
    98 "Don't know"
;
label define HV124   
    97 "Inconsistent"
    98 "Don't know"
;
label define HV125   
     0 "No"
     1 "Yes"
;
label define HV126   
     0 "No education, preschool"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "Don't know"
;
label define HV127   
    98 "Don't know"
;
label define HV128   
    97 "Inconsistent"
    98 "Don't know"
;
label define HV129   
     0 "Never attended"
     1 "Entered school"
     2 "Advanced"
     3 "Repeating"
     4 "Drop-out"
     5 "Left school 2+ years ago"
     8 "Don't know"
;
label define HV140   
     0 "Neither certificate or registered"
     1 "Has certificate"
     2 "Registered"
     8 "Don't know"
;
label define SH08    
     0 "Never married"
     1 "Currently married"
     2 "Married, but Gauna not performed"
     3 "Widowed"
     4 "Divorced"
     5 "Separated"
     6 "Deserted"
     8 "Don't know"
;
label define SH21A   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define SH24    
     0 "Not listed as suffering from TB"
     1 "Yes"
;
label define SH24A   
     0 "No place"
     1 "Yes, public sector only"
     2 "Yes, private sector only"
     3 "Yes, both sectors"
     8 "Don't know"
;
label define SHB12A  
     0 "No"
     1 "Yes"
;
label define SHB12B  
     0 "No"
     1 "Yes"
;
label define SHB12C  
     0 "No"
     1 "Yes"
;
label define SHB12D  
     0 "No"
     1 "Yes"
;
label define SHB13   
    99 "Missing"
;
label define SHB14   
     1 "Small: 17cm-22cm"
     2 "Medium: 23cm-31cm"
     3 "Large: 32cm-42cm"
;
label define SHB15H  
    99 "Missing"
;
label define SHB15M  
    99 "Missing"
;
label define SHB16S  
   994 "Refused"
   995 "Technical problem"
   996 "Other"
;
label define SHB16D  
   994 "Refused"
   995 "Technical problem"
   996 "Other"
;
label define SHB17   
     0 "No"
     1 "Yes"
;
label define SHB18   
     0 "No"
     1 "Yes"
;
label define SHB19   
     0 "No"
     1 "Yes"
;
label define SHB22H  
    99 "Missing"
;
label define SHB22M  
    99 "Missing"
;
label define SHB23S  
   994 "Refused"
   995 "Technical problem"
   996 "Other"
;
label define SHB23D  
   994 "Refused"
   995 "Technical problem"
   996 "Other"
;
label define SHB26H  
    99 "Missing"
;
label define SHB26M  
    99 "Missing"
;
label define SHB27S  
   994 "Refused"
   995 "Technical problem"
   996 "Other"
;
label define SHB27D  
   994 "Refused"
   995 "Technical problem"
   996 "Other"
;
label define SHB51   
    99 "Missing"
;
label define SHB52   
    95 "95+ hours ago"
;
label define SHB69H  
    96 "Not tested"
;
label define SHB69M  
    96 "Not tested"
;
label define SHB70   
   499 "499 (mg/dL) +"
   995 "Refused"
   996 "Other"
   998 "Not tested"
;
label define SHBSEL  
     0 "Not selected"
     1 "Selected"
;
label define SH21    
     1 "School too far away"
     2 "Transport not available"
     3 "Further education not considered necessary"
     4 "Required for household work"
     5 "Required for work on farm/family business"
     6 "Required for outside work for payment in cash or kind"
     7 "Costs too much"
     8 "No proper school facilities for girls"
     9 "Not safe to send girls"
    10 "No female teacher"
    11 "Required for care of siblings"
    12 "Not interested in studies"
    13 "Repeated failures"
    14 "Got married"
    15 "Did not get admission"
    96 "Other"
    98 "Don't know"
;
label define SHB10   
     1 "Granted"
     2 "Parent/other responsible refused"
     3 "Respondent refused"
;
label define SHB20   
     1 "Granted"
     2 "Parent/other responsible refused"
     3 "Respondent refused"
;
label define HA2     
  9994 "Not present"
  9995 "Refused"
  9996 "Other"
;
label define HA3     
  9994 "Not present"
  9995 "Refused"
  9996 "Other"
;
label define HA4     
  9998 "Flagged cases"
;
label define HA5     
  9998 "Flagged cases"
;
label define HA6     
 99998 "Flagged cases"
;
label define HA11    
  9998 "Flagged cases"
;
label define HA12    
 99998 "Flagged cases"
;
label define HA12A   
 99998 "Flagged cases"
;
label define HA12B   
 99998 "Flagged cases"
;
label define HA13    
     0 "Measured"
     3 "Not present"
     4 "Refused"
     6 "Other"
;
label define HA33    
     1 "Month and year - information complete"
     2 "Month and age - year imputed"
     3 "Year and age - month imputed"
     4 "Year and age - year ignored"
     5 "Year - age/month imputed"
     6 "Age - year/month imputed"
     7 "Month - age/year imputed"
     8 "None - all imputed"
;
label define HA35    
     0 "Doesn't smoke"
    80 "80+"
    94 "Smokes pipes, cigars, etc"
;
label define HA40    
  9998 "Flagged cases"
;
label define HA41    
  9998 "Flagged cases"
;
label define HA50    
     1 "Under age 18"
     2 "Age 18 or older"
;
label define HA51    
     0 "Not in household"
;
label define HA52    
     1 "Granted"
     2 "Parent/other responsible refused"
     3 "Respondent refused"
;
label define HA53    
   994 "Not present"
   995 "Refused"
   996 "Other"
   998 "Not tested"
;
label define HA54    
     0 "No/don't know"
     1 "Yes"
;
label define HA55    
     0 "Measured"
     3 "Not present"
     4 "Refused"
     6 "Other"
;
label define HA56    
   994 "Not present"
   995 "Refused"
   996 "Other"
   998 "Not tested"
;
label define HA57    
     1 "Severe"
     2 "Moderate"
     3 "Mild"
     4 "Not anemic"
;
label define HA58    
     0 "No"
     1 "Yes"
;
label define HA60    
     1 "Never in union"
     2 "Other"
;
label define HA61    
     1 "Granted"
     2 "Parent/other responsible refused"
     3 "Respondent refused"
     4 "Sample not tested/lost/not enough DBS"
;
label define HA63    
     1 "Blood taken"
     2 "Not present"
     3 "Refused"
     4 "Sample not tested/lost/damaged/insufficient"
     5 "Not enough DBS to complete protocol"
     6 "Other"
;
label define HA64    
     1 "Granted"
     2 "Parent/other responsible refused"
     3 "Respondent refused"
;
label define HA65    
     1 "Completed"
     2 "Not at home"
     3 "Postponed"
     4 "Refused"
     5 "Partly completed"
     6 "Incapacitated"
     7 "Other"
;
label define HA66    
     0 "No education"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "Don't know"
;
label define HA67    
    98 "Don't know"
;
label define HA68    
     0 "No education"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "Don't know"
;
label define HA70    
   999 "Missing"
;
label define HC2     
  9994 "Not present"
  9995 "Refused"
  9996 "Other"
;
label define HC3     
  9994 "Not present"
  9995 "Refused"
  9996 "Other"
;
label define HC4     
  9998 "Flagged cases"
;
label define HC5     
  9998 "Flagged cases"
;
label define HC6     
 99998 "Flagged cases"
;
label define HC7     
  9998 "Flagged cases"
;
label define HC8     
  9998 "Flagged cases"
;
label define HC9     
 99998 "Flagged cases"
;
label define HC10    
  9998 "Flagged cases"
;
label define HC11    
  9998 "Flagged cases"
;
label define HC12    
 99998 "Flagged cases"
;
label define HC13    
     0 "Measured"
     3 "Not present"
     4 "Refused"
     6 "Other"
;
label define HC15    
     0 "Not measured"
     1 "Lying"
     2 "Standing"
;
label define HC16    
    97 "Inconsistent"
    98 "Don't know"
;
label define HC27    
     1 "Male"
     2 "Female"
;
label define HC30    
    97 "Inconsistent"
    98 "Don't know"
;
label define HC31    
  9997 "Inconsistent"
  9998 "Don't know"
;
label define HC33    
     1 "Month and year - information complete"
     2 "Month and age - year imputed"
     3 "Year and age - month imputed"
     5 "Year - age/month imputed"
     6 "Age - year/month imputed"
     7 "Month - age/year imputed"
     8 "None - all imputed"
;
label define HC51    
     0 "Not in household"
;
label define HC52    
     1 "Granted"
     2 "Refused"
     3 "Granted but no signature"
;
label define HC53    
   994 "Not present"
   995 "Refused"
   996 "Other"
;
label define HC55    
     0 "Measured"
     3 "Not present"
     4 "Refused"
     6 "Other"
;
label define HC56    
   997 "Inconsistent"
;
label define HC57    
     1 "Severe"
     2 "Moderate"
     3 "Mild"
     4 "Not anemic"
;
label define HC58    
     0 "No"
     1 "Yes"
;
label define HC60    
   993 "Mother not de facto"
   994 "Incomplete woman's interview"
   995 "Not in household"
;
label define HC61    
     0 "No education"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "Don't know"
;
label define HC62    
    98 "Don't know"
;
label define HC63    
   999 "Missing"
;
label define HC64    
    99 "Missing"
;
label define HC68    
     0 "No education"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "Don't know"
;
label define HC70    
  9996 "Height out of plausible limits"
  9997 "Age in days out of plausible limits"
  9998 "Flagged cases"
;
label define HC71    
  9996 "Height out of plausible limits"
  9997 "Age in days out of plausible limits"
  9998 "Flagged cases"
;
label define HC72    
  9996 "Height out of plausible limits"
  9997 "Age in days out of plausible limits"
  9998 "Flagged cases"
;
label define HC73    
  9996 "Height out of plausible limits"
  9997 "Age in days out of plausible limits"
  9998 "Flagged cases"
;
label define HB2     
  9994 "Not present"
  9995 "Refused"
  9996 "Other"
;
label define HB3     
  9994 "Not present"
  9995 "Refused"
  9996 "Other"
;
label define HB4     
  9998 "Flagged cases"
;
label define HB5     
  9998 "Flagged cases"
;
label define HB6     
 99998 "Flagged cases"
;
label define HB11    
  9998 "Flagged cases"
;
label define HB12    
 99998 "Flagged cases"
;
label define HB12A   
 99998 "Flagged cases"
;
label define HB12B   
 99998 "Flagged cases"
;
label define HB13    
     0 "Measured"
     3 "Not present"
     4 "Refused"
     6 "Other"
;
label define HB33    
     1 "Month and year - information complete"
     2 "Month and age - year imputed"
     3 "Year and age - month imputed"
     4 "Year and age - year ignored"
     5 "Year - age/month imputed"
     6 "Age - year/month imputed"
     7 "Month - age/year imputed"
     8 "None - all imputed"
;
label define HB35    
     0 "Doesn't smoke"
    80 "80+"
    94 "Smokes pipes, cigars, etc"
    98 "Don't know"
;
label define HB40    
  9998 "Flagged cases"
;
label define HB41    
  9998 "Flagged cases"
;
label define HB50    
     1 "Under age 18"
     2 "Age 18 or older"
;
label define HB51    
     0 "Not in household"
;
label define HB52    
     1 "Granted"
     2 "Parent/other responsible refused"
     3 "Respondent refused"
;
label define HB53    
   994 "Not present"
   995 "Refused"
   996 "Other"
   998 "Not tested"
;
label define HB55    
     0 "Measured"
     3 "Not present"
     4 "Refused"
     6 "Other"
;
label define HB56    
   997 "Inconsistent"
;
label define HB57    
     1 "Severe"
     2 "Moderate"
     3 "Mild"
     4 "Not anemic"
;
label define HB58    
     0 "No"
     1 "Yes"
;
label define HB60    
     1 "Never in union"
     2 "Other"
;
label define HB61    
     1 "Granted"
     2 "Parent/other responsible refused"
     3 "Respondent refused"
     4 "Sample not tested/lost/not enough DBS"
;
label define HB63    
     1 "Blood taken"
     2 "Not present"
     3 "Refused"
     4 "Sample not tested/lost/damaged/insufficient"
     5 "Not enough DBS to complete protocol"
     6 "Other"
;
label define HB64    
     1 "Granted"
     2 "Parent/other responsible refused"
     3 "Respondent refused"
;
label define HB65    
     1 "Completed"
     2 "Not at home"
     3 "Postponed"
     4 "Refused"
     5 "Partly completed"
     6 "Incapacitated"
     7 "Other"
;
label define HB66    
     0 "No education"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "Don't know"
;
label define HB67    
    98 "Don't know"
;
label define HB68    
     0 "No education"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "Don't know"
;
label define HB70    
   999 "Missing"
;
label define HML3    
     0 "Not seen"
     1 "Yes, seen"
;
label define HML4    
    96 "More than 3 years ago"
    98 "Don't know"
;
label define HML5    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HML6    
     0 "Not pretreated"
     1 "Pretreated, permanent treatment"
     2 "Pretreated, requiring future treatment"
     6 "Other"
     8 "Don't know"
;
label define HML7    
    11 "Dawa Plus"
    12 "Duranet"
    13 "Interceptor"
    14 "Lifenet"
    15 "Magnet"
    16 "Netprotect"
    17 "Olyset"
    18 "Permanet"
    19 "Royal Sentry"
    20 "Yorkool"
    26 "Other/don't know brand (LLIN)"
    30 "Pretreated net"
    96 "Other brand"
    98 "Don't know brand"
;
label define HML8    
     0 "No"
     1 "Yes"
     2 "Permanent net"
     8 "Not sure"
;
label define HML9    
    95 "25+ months ago"
    96 "More than 3 years ago"
    98 "Don't know"
;
label define HML10   
     0 "No, don't know"
     1 "Yes"
;
label define HML11   
     5 "5+"
;
label define HML21   
     0 "No"
     1 "Yes"
     8 "Not sure (DK)"
;
label define HMLA    
     0 "No one"
;
label define HMLB    
    99 "Missing"
;
label define HMLC    
    99 "Missing"
;
label define HML12   
     0 "Did not sleep under a net"
     1 "Only treated (ITN) nets"
     2 "Both treated (ITN) and untreated nets"
     3 "Only untreated nets"
;
label define HML13   
     0 "Did not sleep under net"
;
label define HML16   
    97 "97+"
    98 "Don't know"
;
label define HML17   
     0 "No data from Individual file"
     1 "Month and year - information complete"
     2 "Month and age - year imputed"
     3 "Year and age - month imputed"
     4 "Year and age - year ignored"
     5 "Year - age/month imputed"
     6 "Age - year/month imputed"
     7 "Month - age/year imputed"
     8 "None - all imputed"
;
label define HML18   
     0 "Not pregnant, don't know"
     1 "Pregnant"
;
label define HML19   
     0 "No"
     1 "Yes"
;
label define HML20   
     0 "No"
     1 "Yes"
;
label define HML30   
     0 "Not in household"
;
label define HML31   
     1 "Granted"
     2 "Refused"
;
label define HML32   
     0 "Negative"
     1 "Positive"
     6 "Test undetermined"
     7 "Sample not found in lab database"
;
label define HML32A  
     0 "No"
     1 "Yes"
;
label define HML32B  
     0 "No"
     1 "Yes"
;
label define HML32C  
     0 "No"
     1 "Yes"
;
label define HML32D  
     0 "No"
     1 "Yes"
;
label define HML32E  
     0 "No"
     1 "Yes"
;
label define HML32F  
     0 "No"
     1 "Yes"
;
label define HML32G  
     0 "No"
     1 "Yes"
;
label define HML33   
     0 "Measured"
     3 "Not present"
     4 "Refused"
     6 "Other"
;
label define HML35   
     0 "Negative"
     1 "Positive"
;

#delimit cr
label values hv003    HV003   
label values hv015    HV015   
label values hv020    HV020   
label values hv024    HV024   
label values hv025    HV025   
label values hv026    HV026   
label values hv027    HV027   
label values hv042    HV042   
label values hv044    HV044   
label values hv201    HV201   
label values hv202    HV202   
label values hv204    HV204   
label values hv205    HV205   
label values hv206    HV206   
label values hv207    HV207   
label values hv208    HV208   
label values hv209    HV209   
label values hv210    HV210   
label values hv211    HV211   
label values hv212    HV212   
label values hv213    HV213   
label values hv214    HV214   
label values hv215    HV215   
label values hv216    HV216   
label values hv217    HV217   
label values hv219    HV219   
label values hv220    HV220   
label values hv221    HV221   
label values hv225    HV225   
label values hv226    HV226   
label values hv227    HV227   
label values hv228    HV228   
label values hv230a   HV230A  
label values hv230b   HV230B  
label values hv232    HV232   
label values hv232b   HV232B  
label values hv232c   HV232C  
label values hv232d   HV232D  
label values hv232e   HV232E  
label values hv232y   HV232Y  
label values hv234    HV234   
label values hv234a   HV234A  
label values hv235    HV235   
label values hv236    HV236   
label values hv237    HV237   
label values hv237a   HV237A  
label values hv237b   HV237B  
label values hv237c   HV237C  
label values hv237d   HV237D  
label values hv237e   HV237E  
label values hv237f   HV237F  
label values hv237g   HV237G  
label values hv237h   HV237H  
label values hv237i   HV237I  
label values hv237j   HV237J  
label values hv237k   HV237K  
label values hv237x   HV237X  
label values hv237z   HV237Z  
label values hv238    HV238   
label values hv239    HV239   
label values hv240    HV240   
label values hv241    HV241   
label values hv242    HV242   
label values hv243a   HV243A  
label values hv243b   HV243B  
label values hv243c   HV243C  
label values hv243d   HV243D  
label values hv244    HV244   
label values hv245    HV245   
label values hv246    HV246   
label values hv246a   HV246A  
label values hv246b   HV246B  
label values hv246c   HV246C  
label values hv246d   HV246D  
label values hv246e   HV246E  
label values hv246f   HV246F  
label values hv246g   HV246G  
label values hv246h   HV246H  
label values hv246i   HV246I  
label values hv246j   HV246J  
label values hv246k   HV246K  
label values hv247    HV247   
label values hv252    HV252   
label values hv253    HV253   
label values hv253a   HV253A  
label values hv253b   HV253B  
label values hv253c   HV253C  
label values hv253d   HV253D  
label values hv253e   HV253E  
label values hv253f   HV253F  
label values hv253g   HV253G  
label values hv253h   HV253H  
label values hv253x   HV253X  
label values hv253z   HV253Z  
label values hv270    HV270   
label values hml1     HML1    
label values shdistri SHDISTRI
label values shslumc  SHSLUMC 
label values shslumo  SHSLUMO 
label values shconsent SHCONSENT
label values shlangq  SHLANGQ 
label values shlangrm SHLANGRM
label values shlangi  SHLANGI 
label values shtransl SHTRANSL
label values sh23     SH23    
label values sh34     SH34    
label values sh35     SH35    
label values sh36     SH36    
label values sh37b    SH37B   
label values sh37c    SH37C   
label values sh37d    SH37D   
label values sh37e    SH37E   
label values sh37f    SH37F   
label values sh37g    SH37G   
label values sh37i    SH37I   
label values sh37j    SH37J   
label values sh37k    SH37K   
label values sh37n    SH37N   
label values sh37o    SH37O   
label values sh37q    SH37Q   
label values sh37r    SH37R   
label values sh37x    SH37X   
label values sh37y    SH37Y   
label values sh37z    SH37Z   
label values sh46     SH46    
label values sh47     SH47    
label values sh49     SH49    
label values hv245i   HV245I  
label values sh52a    SH52A   
label values sh52b    SH52B   
label values sh52c    SH52C   
label values sh52d    SH52D   
label values sh52e    SH52E   
label values sh52f    SH52F   
label values sh54     SH54    
label values sh55a    SH55A   
label values sh55b    SH55B   
label values sh55c    SH55C   
label values sh55d    SH55D   
label values sh55e    SH55E   
label values sh55f    SH55F   
label values sh55g    SH55G   
label values sh55h    SH55H   
label values sh55x    SH55X   
label values sh56     SH56    
label values sh57a    SH57A   
label values sh57b    SH57B   
label values sh57c    SH57C   
label values sh57d    SH57D   
label values sh57e    SH57E   
label values sh57x    SH57X   
label values sh58     SH58    
label values sh61a    SH61A   
label values sh61b    SH61B   
label values sh61c    SH61C   
label values sh61x    SH61X   
label values sh61z    SH61Z   
label values sh70     SH70    
label values sh39     SH39    
label values shnfhs2  SHNFHS2 
label values shstruc  SHSTRUC 
label values sh50     SH50    
label values sh51     SH51    
label values agland   AGLAND  
label values sv270s   SV270S  
label values sv270u   SV270U  
label values sv270us  SV270US 
label values sv270r   SV270R  
label values sv270rs  SV270RS 
label values sh50u    SH50U   
label values shphase  SHPHASE 
label values hv101    HV101   
label values hv102    HV102   
label values hv103    HV103   
label values hv104    HV104   
label values hv105    HV105   
label values hv106    HV106   
label values hv107    HV107   
label values hv108    HV108   
label values hv109    HV109   
label values hv110    HV110   
label values hv111    HV111   
label values hv112    HV112   
label values hv113    HV113   
label values hv114    HV114   
label values hv115    HV115   
label values hv116    HV116   
label values hv117    HV117   
label values hv118    HV118   
label values hv120    HV120   
label values hv121    HV121   
label values hv122    HV122   
label values hv123    HV123   
label values hv124    HV124   
label values hv125    HV125   
label values hv126    HV126   
label values hv127    HV127   
label values hv128    HV128   
label values hv129    HV129   
label values hv140    HV140   
label values sh08     SH08    
label values sh21a    SH21A   
label values sh24     SH24    
label values sh24a    SH24A   
label values shb12a   SHB12A  
label values shb12b   SHB12B  
label values shb12c   SHB12C  
label values shb12d   SHB12D  
label values shb14    SHB14   
label values shb16s   SHB16S  
label values shb16d   SHB16D  
label values shb17    SHB17   
label values shb18    SHB18   
label values shb19    SHB19   
label values shb23s   SHB23S  
label values shb23d   SHB23D  
label values shb27s   SHB27S  
label values shb27d   SHB27D  
label values shb52    SHB52   
label values shb69h   SHB69H  
label values shb69m   SHB69M  
label values shb70    SHB70   
label values shbsel   SHBSEL  
label values sh21     SH21    
label values shb10    SHB10   
label values shb20    SHB20   
label values ha2      HA2     
label values ha3      HA3     
label values ha4      HA4     
label values ha5      HA5     
label values ha6      HA6     
label values ha11     HA11    
label values ha12     HA12    
label values ha12a    HA12A   
label values ha12b    HA12B   
label values ha13     HA13    
label values ha33     HA33    
label values ha35     HA35    
label values ha40     HA40    
label values ha41     HA41    
label values ha50     HA50    
label values ha51     HA51    
label values ha52     HA52    
label values ha53     HA53    
label values ha54     HA54    
label values ha55     HA55    
label values ha56     HA56    
label values ha57     HA57    
label values ha58     HA58    
label values ha60     HA60    
label values ha61     HA61    
label values ha63     HA63    
label values ha64     HA64    
label values ha65     HA65    
label values ha66     HA66    
label values ha67     HA67    
label values ha68     HA68    
label values hc2      HC2     
label values hc3      HC3     
label values hc4      HC4     
label values hc5      HC5     
label values hc6      HC6     
label values hc7      HC7     
label values hc8      HC8     
label values hc9      HC9     
label values hc10     HC10    
label values hc11     HC11    
label values hc12     HC12    
label values hc13     HC13    
label values hc15     HC15    
label values hc16     HC16    
label values hc27     HC27    
label values hc30     HC30    
label values hc31     HC31    
label values hc33     HC33    
label values hc51     HC51    
label values hc52     HC52    
label values hc53     HC53    
label values hc55     HC55    
label values hc56     HC56    
label values hc57     HC57    
label values hc58     HC58    
label values hc60     HC60    
label values hc61     HC61    
label values hc62     HC62    
label values hc68     HC68    
label values hc70     HC70    
label values hc71     HC71    
label values hc72     HC72    
label values hc73     HC73    
label values hb2      HB2     
label values hb3      HB3     
label values hb4      HB4     
label values hb5      HB5     
label values hb6      HB6     
label values hb11     HB11    
label values hb12     HB12    
label values hb12a    HB12A   
label values hb12b    HB12B   
label values hb13     HB13    
label values hb33     HB33    
label values hb35     HB35    
label values hb40     HB40    
label values hb41     HB41    
label values hb50     HB50    
label values hb51     HB51    
label values hb52     HB52    
label values hb53     HB53    
label values hb55     HB55    
label values hb56     HB56    
label values hb57     HB57    
label values hb58     HB58    
label values hb60     HB60    
label values hb61     HB61    
label values hb63     HB63    
label values hb64     HB64    
label values hb65     HB65    
label values hb66     HB66    
label values hb67     HB67    
label values hb68     HB68    
label values hml3     HML3    
label values hml4     HML4    
label values hml5     HML5    
label values hml6     HML6    
label values hml7     HML7    
label values hml8     HML8    
label values hml9     HML9    
label values hml10    HML10   
label values hml11    HML11   
label values hml21    HML21   
label values hmla     HMLA    
label values hml12    HML12   
label values hml13    HML13   
label values hml16    HML16   
label values hml17    HML17   
label values hml18    HML18   
label values hml19    HML19   
label values hml20    HML20   
label values hml30    HML30   
label values hml31    HML31   
label values hml32    HML32   
label values hml32a   HML32A  
label values hml32b   HML32B  
label values hml32c   HML32C  
label values hml32d   HML32D  
label values hml32e   HML32E  
label values hml32f   HML32F  
label values hml32g   HML32G  
label values hml33    HML33   
label values hml35    HML35   
